#!/bin/bash

SAVE_PATH=$HOME/media/imgs/

LAST_FILE=$SAVE_PATH.last

mkdir -p "$SAVE_PATH"

ARGV=("$@")

while [ $# -gt 0 ]; do
	case "$1" in
		-n|--name) FILE=$SAVE_PATH$2.png; shift ;;
	esac
	shift
done

[ -z "$FILE" ] && FILE=$(date +$SAVE_PATH%Y%m%d-%H%M%S.png)

set -- "${ARGV[@]}"

# Handle quick actions that don't need a new screenshot
while [ $# -gt 0 ]; do
	case "$1" in
		-c|--copy)
			xclip < "$LAST_FILE"
			exit 0 ;;
		-l|--last)
			cat "$LAST_FILE" && echo
			exit 0 ;;
		-v|--view)
			if [ -z "$2" ]; then
				feh "$(cat "$LAST_FILE")" &>/dev/null &
			else
				feh "$SAVE_PATH$2.png" &>/dev/null &
			fi
			exit 0 ;;
	esac
	shift
done

set -- "${ARGV[@]}"

# Take screenshot
maim -u -n 1 -s "$FILE"

echo -n "$FILE" > "$LAST_FILE"

# Post-capture actions
while [ $# -gt 0 ]; do
	case "$1" in
		-r|--rename)
			result=$(mktemp)
			prevloc=$(mktemp)
			ROFI_SAVE_DIR="$SAVE_PATH" ROFI_SAVE_EXT=.png ROFI_SAVE_RESULT="$result" ROFI_SAVE_PREVLOC="$prevloc" rofi -show save -modi "save:rofi-save" >/dev/null 2>&1
			new=$(cat "$result")
			rm -f "$result" "$prevloc"
			old=$(cat "$LAST_FILE")
			if [ -n "$new" ] && [ "$new" != "$old" ]; then
				if [ -e "$new" ]; then
					confirm=$(echo -e "Y\nn" | rofi -dmenu -p "overwrite $(basename "$new")? [Y/n]" 2>/dev/null)
					[ "$confirm" = "n" ] && new=""
				fi
				if [ -n "$new" ]; then
					mkdir -p "$(dirname "$new")"
					mv "$old" "$new"
					echo -n "$new" > "$LAST_FILE"
				fi
			fi
			xclip >&- 2>&- < "$LAST_FILE"
			cat "$LAST_FILE" ;;
		-e|--echo)
			cat "$LAST_FILE" ;;
		-x|--xclip)
			xclip < "$LAST_FILE" & ;;
		-p|--play)
			feh "$(cat "$LAST_FILE")" &>/dev/null & ;;
	esac
	shift
done
