#!/bin/bash
# rvid X Y W H FILE: record a screen region with desktop audio until interrupted

X=$1 Y=$2 W=$3 H=$4 FILE=$5

# Auto-detect default audio monitor
# *change pulse source for mic*
# mic alsa_input.usb-Razer_Inc_Razer_Seiren_Mini_UC2447L03303339-00.mono-fallback
AUDIO_SOURCE="$(pactl get-default-sink).monitor"

exec wf-recorder -y -g "$X,$Y ${W}x$H" -r 60 --audio="$AUDIO_SOURCE" \
	-c libx264 -p preset=veryfast -p crf=22 -p tune=zerolatency -x yuv420p \
	-C aac -f "$FILE"
